### ISSUE TITLE
docker-compose启动报错

### ISSUE THREAD

**Issue by WangBoee** [lyx9805/MemoTgBot#1]
使用docker-compose启动报错，配置参考的readme:
```yaml
version: "3.3"
services:
  memotgbot:
    image: lyx98/memotgbot:latest
    container_name: memotgbot
    environment:
      - BOT_TOKEN=mytoken
      - CHAT_ID=myid
      - CHANNEL_ID=mychannelid
      - MEMO_API=myapi
    restart: always
```
`docker logs memotgbot` 查看日志显示以下内容:
```
exec /usr/local/bin/python: exec format error
exec /usr/local/bin/python: exec format error
exec /usr/local/bin/python: exec format error
```
---

docker-compose version:
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
